version: '3.5'

services:
  postgres:
    env_file:
      - .env.development
    container_name: postgres_container
    image: postgres
    volumes:
       - book-service-postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
volumes:
  book-service-postgres: