version: '3.5'

services:
  postgres:
    env_file:
      - .env.development
    container_name: postgres_container
    image: postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    env_file:
        - .env.development
    container_name: pgadmin_container
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  book-service-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app

networks:
  postgres:
    driver: bridge