name: 'CI'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up NodeJS version 16.15.1
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16.15.1
      - name: Install Yarn
        run: npm install --location=global yarn
      - name: Install dependencies
        run: yarn
      - name: Linter
        run: yarn lint
  build-for-testing:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker image build -f Dockerfile.dev -t ${{ secrets.DOCKER_HUB_USERNAME }}/book-service-testing:latest .
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Running Test
        run: docker container run -e CI=true ${{ secrets.DOCKER_HUB_USERNAME }}/book-service-testing yarn test
  build-prod:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build production
        run: docker image build -t ${{ secrets.DOCKER_HUB_USERNAME }}/book-service-prod:latest .
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/book-service-prod:latest
  
      