name: 'CI'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-for-lint-and-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        # run: docker image build -f Dockerfile.dev -t ${{ secrets.DOCKER_HUB_USERNAME }}/book-service-testing .
        run: docker image build -f Dockerfile.dev -t indiedevs/book-service-image-for-jest-testing .
      - name: Lint
        run: docker container run -e CI=true indiedevs/book-service-image-for-jest-testing yarn lint
      - name: Test
        # run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/book-service-prod
        run: docker container run -e CI=true indiedevs/book-service-image-for-jest-testing yarn test
  build-prod:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    needs: [build-for-lint-and-test]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          # username: ${{ secrets.DOCKER_HUB_USERNAME }}
          username: indiedevs
          # password: ${{ secrets.DOCKER_HUB_TOKEN }}
          password: 'c3a82913-3b96-4d76-8719-16815ea981ee'
      - name: Build production
        # run: docker image build -t ${{ secrets.DOCKER_HUB_USERNAME }}/book-service-prod:latest .
        run: docker image build -t indiedevs/book-service-prod .
      - name: Push to Docker Hub
        # run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/book-service-prod:latest
        run: docker push indiedevs/book-service-prod